# Generated by Django 4.2 on 2024-10-25 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReclamationRapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('contenu', models.TextField()),
            ],
        ),
    ]
