# Generated by Django 5.1.1 on 2024-10-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_remove_article_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='moderated',
            field=models.BooleanField(default=False),
        ),
    ]
