# Generated by Django 4.2 on 2024-10-23 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userprofile_face_encoding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='face_encoding',
        ),
    ]
