# Generated by Django 4.2 on 2024-10-25 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_userprofile_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='face_encoding',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
